"""empty message

Revision ID: f141f4417068
Revises: 7a5c955901d1
Create Date: 2023-06-10 21:46:01.969295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f141f4417068'
down_revision = '7a5c955901d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'created_on')
    # ### end Alembic commands ###
